# Dependencies
markdown:         redcarpet
highlighter:      rouge #pygments

# Permalinks
permalink:        pretty

# Setup
title:            rvirmoors
tagline:          'music computing research & design'
description:      'Interactive music researcher/designer. Synchronisation, dynamic processes, interaction design, electric guitar.'
url:              https://rvirmoors.github.io
baseurl:          "/"

author:
  name:           'Grigore Burloiu'
  url:            https://github.com/RVirmoors

paginate:         5

gems:             [jekyll-paginate]

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
