theme:            minima
minima:
  skin:           rv
  date_format:    "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: growlerpig
    github:  rvirmoors

show_excerpts: true # set to true to show excerpts on the homepage


# Dependencies
markdown:         kramdown
highlighter:      rouge #pygments

# Permalinks
permalink:        pretty

# Setup
title:            rvirmoors
description:      >
  Creative code, interactive music.
  
url:              https://rvirmoors.github.io
baseurl:          /

author:
  name:           'Grigore Burloiu'
  email:          grigore.burloiu@unatc.ro

plugins:
 - jekyll-feed
 - jekyll-seo-tag