# Dependencies
#markdown:         redcarpet
highlighter:      rouge #pygments

# Permalinks
permalink:        pretty

# Setup
title:            rvirmoors
tagline:          'Grigore Burloiu // Interactive music research + design.'
description:      'dynamic music <a href="/2018/07/03/dynamic-music/">.</a>'
url:              https://rvirmoors.github.io
baseurl:          /

author:
  name:           'Grigore Burloiu'
  url:            https://github.com/RVirmoors

paginate:         5

gems:             [jekyll-paginate]

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
